# Generated by Django 3.2.12 on 2022-03-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1994-03-07'),
            preserve_default=False,
        ),
    ]
