# Generated by Django 3.2.12 on 2022-02-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
                ('simg', models.ImageField(upload_to='thumb')),
                ('sdes', models.TextField()),
            ],
        ),
    ]
