# Generated by Django 3.2.12 on 2022-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nme1', models.CharField(max_length=250)),
                ('imh1', models.ImageField(upload_to='team_pic')),
                ('dsc1', models.TextField()),
            ],
        ),
    ]
